name: Auto-Update Documentation Submodule

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - 'doks/**'
      - 'docs/**'
  workflow_dispatch:

jobs:
  update-docs-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Update doks submodule
      run: |
        # Make the script executable
        chmod +x scripts/auto-update-docs-submodule.sh

        # Run the auto-update script
        ./scripts/auto-update-docs-submodule.sh

    - name: Check for changes
      id: check-changes
      run: |
        if git diff --quiet HEAD~1 HEAD; then
          echo "has-changes=false" >> $GITHUB_OUTPUT
        else
          echo "has-changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Push changes
      if: steps.check-changes.outputs.has-changes == 'true'
      run: |
        git push origin ${{ github.ref_name }}

    - name: Comment on PR
      if: github.event_name == 'pull_request' && steps.check-changes.outputs.has-changes == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '📚 Documentation submodule has been automatically updated with the latest changes.'
          })
